name: Deploy Vue App

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VITE_FB_API_KEY: ${{ secrets.VITE_FB_API_KEY }}
      VITE_FB_AUTH_DOMAIN: ${{ secrets.VITE_FB_AUTH_DOMAIN }}
      VITE_FB_PROJECT_ID: ${{ secrets.VITE_FB_PROJECT_ID }}
      VITE_FB_STORAGE_BUCKET: ${{ secrets.VITE_FB_STORAGE_BUCKET }}
      VITE_FB_MESSAGING_SENDER_ID: ${{ secrets.VITE_FB_MESSAGING_SENDER_ID }}
      VITE_FB_APP_ID: ${{ secrets.VITE_FB_APP_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build

      - name: Clean remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/app/dist
            rm -rf *

      - name: Upload build files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          source: dist/*
          target: /var/www/app

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx